# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
  - name: About 
    url: ''
    weight: 10
    identifier: LLL
  - name: "About"
    url: ''
    weight: 11
    parent: LLL
  - name: "In 5 minutes: presentation"
    url: ../slides/listen-local-bulgaria-intro//
    weight: 12
    parent: LLL
  - name: Blog
    url: post
    weight: 20
  - name: Community
    url: ""
    weight: 30
    identifier: community
  - name: Musicians
    url: /musicians/
    weight: 31
    parent: community
  - name: Contributors
    url: /contributors/
    weight: 32
    parent: community
  - name: Music
    url: ""
    identifier: Music
    weight: 40
  - name: Genres
    url: /genre/
    weight: 41
    parent: Music
  - name: Bands
    url: /bands/
    weight: 42
    parent: Music
  - name: Solo acts & projects
    url: /solo/
    weight: 43
    parent: Music
  - name: Music Works & Recordings
    url: /music_work/
    weight: 46
    parent: Music
  - name: Database
    url: ""
    weight: 50
    identifier: database
  - name: ğŸ—ƒï¸ Write-in Database
    url: ../data/write-in/
    weight: 51
    parent: database
  - name: âœ… Opt-in Database
    url: ../data/opt-in/
    weight: 52
    parent: database
  - name: Contact & Events
    url: '#contact'
    weight: 90
    identifier: Contact
  - name: Get in touch
    url: '/contact'
    weight: 90
    parent: Contact
  - name: Public talks
    url: /event
    weight: 92
    parent: Contact
